// export default projects = [
//   {
//     id: 1,
//     ProjectId: "NZ1911180013",
//     ProjectCreatorEmail: "ami.durlabh@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Omnibus November #2",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: true,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "juliet.martin@nielsen.com,jason.kok@nielsen.com,ami.durlabh@nielsen.com,beena.mitha@nielsen.com",
//     ProjectResourcesFolderId: "1swE7fdZYX-hDPPEYFh-mMrGrwFpCRa84",
//     CostingsFolderId: "1ii8qVAPhY6ig5wrwXhdhHKFlul7s6nII",
//     CommissionedProfileId: 18,
//     CommissionedBy: "ami.durlabh@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 2,
//     ProjectId: "NZ1911180014",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Melissa test",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1QpurMrZE13Y3Tov406zGucYOnWYmyfHG",
//     CostingsFolderId: "15kHov5_E7IqNYAGbljPxOwr0_O6ePOZf",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 3,
//     ProjectId: "AU1911180015",
//     ProjectCreatorEmail: "darshana.geeganage@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "PepsiCo_Employer Branding_Sep 19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "2",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "",
//     ProjectResourcesFolderId: "1KEyX3YWoYyZ6woaSdjSFWVQlxcjj1las",
//     CostingsFolderId: "1r7N8xGBAHPUpJR8YnMV1eWfZtxSgxeuU",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 4,
//     ProjectId: "NZ1911190016",
//     ProjectCreatorEmail: "antoinette.hastings@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "qol 2018 test",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ2",
//     IsSyndicated: false,
//     Methodology: "FM000019",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "antoinette.hastings@nielsen.com,tessa.hoffman@nielsen.com",
//     ProjectResourcesFolderId: "1KmyF2NlUzZwW57mxTznkMWhzGIo0x1ao",
//     CostingsFolderId: "1nAONvR3vLjaAz9WR07texrkW7NnwEXbZ",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 5,
//     ProjectId: "NZ1911190017",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Quality of Life 2020",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ2",
//     IsSyndicated: true,
//     Methodology: "FM000040,FM000002",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "tessa.hoffman@nielsen.com,antoinette.hastings@nielsen.com,cathy.cross@nielsen.com,roman.konopka@nielsen.com,ria.goble@nielsen.com",
//     ProjectResourcesFolderId: "1TLJzfQaeDVJELP9Rc9FA8__UTsOUxx2L",
//     CostingsFolderId: "1H6nbCNms5JvGEDb5fcoF_f7aZDhKppTw",
//     CommissionedProfileId: 220,
//     CommissionedBy: "tessa.hoffman@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "cathy.cross@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 6,
//     ProjectId: "NZ1911200018",
//     ProjectCreatorEmail: "aashish.negi@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "CI_WorkSafe_Guidance materials 2019_Nov19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ2",
//     IsSyndicated: false,
//     Methodology: null,
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "roman.konopka@nielsen.com",
//     ProjectResourcesFolderId: null,
//     CostingsFolderId: null,
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: false,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 7,
//     ProjectId: "NZ1911200019",
//     ProjectCreatorEmail: "roman.konopka@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "CI_WorkSafe_Guidance materials 2019_Nov19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ2",
//     IsSyndicated: false,
//     Methodology: "FM000005",
//     ProjectStatus: "5",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "roman.konopka@nielsen.com",
//     ProjectResourcesFolderId: "1lDJC5ahzowQJks5bpOyWEbUYNgKveL0_",
//     CostingsFolderId: "1AfNObj5p5ttIavnnVkiD5_dA4LUkR7Wi",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 8,
//     ProjectId: "AU1911200020",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Sponsorship Impact Analysis",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "ben.x.allen@nielsen.com",
//     ProjectResourcesFolderId: "1WMVSJzPf-lHCaWMW9w-089BPhWPxYTXd",
//     CostingsFolderId: "1guHlZ-riZ4LMSP1IaXvQFouEB5iQadya",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 9,
//     ProjectId: "AU1911200021",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "test",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "12ms8aonBEIEdklYHY9BuTq4xXWiU980Q",
//     CostingsFolderId: "1terbRhvy6oR75oOReg0vToBsJPpxyh4x",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 10,
//     ProjectId: "AU1911200022",
//     ProjectCreatorEmail: "darshana.geeganage@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Delonghi_Brand Health_Oct19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "",
//     ProjectResourcesFolderId: "11dlZ3xc4KowwX412OndbWMtjUPemp1nd",
//     CostingsFolderId: "1WMecfknZZCEulp_bzFnYg2FGSB3UvgKK",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 11,
//     ProjectId: "AU1911210023",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Sponsorship Impact Analysis",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: null,
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "ben.x.allen@nielsen.com",
//     ProjectResourcesFolderId: null,
//     CostingsFolderId: null,
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: false,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 12,
//     ProjectId: "AU1911210024",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName:
//       "Sponsorship Impact Analysis (Sports & MA Training Test Please Ignore)",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "ben.x.allen@nielsen.com,shruthi.babu@nielsen.com",
//     ProjectResourcesFolderId: "1rNBny_GJ0iFwH0_Oe0x5AtDLCwIzrBpl",
//     CostingsFolderId: "1PKmHpEZPlDnbYGWX3iolj6IaEJJYujYp",
//     CommissionedProfileId: 32,
//     CommissionedBy: "melissa.graham@nielsen.com",
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "susan.bonnar@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 13,
//     ProjectId: "AU1911210025",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "test",
//     BusinessUnit: "MA",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: true,
//     Methodology: "FM000040,FM000004,FM000010",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1hkeyu6CXpcH1S0A89qI-1ictkoVvg29y",
//     CostingsFolderId: "1N5x7eVGU63wVDvvHmKvmnjUiSwETIU-j",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 14,
//     ProjectId: "NZ1911210026",
//     ProjectCreatorEmail: "ami.durlabh@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "CI_Plant and Food Research_Customer Satisfaction",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "ian.mills@nielsen.com",
//     ProjectResourcesFolderId: "1OgYY2oXgWQTioJXiJzWdDjgqV8sxiYKx",
//     CostingsFolderId: "1hYFGBq8XXjJ399rc_bbaoVlGNxJLzJyK",
//     CommissionedProfileId: 1963,
//     CommissionedBy: "ami.durlabh@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "stefi.wenas@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: true,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 15,
//     ProjectId: "AU1911210027",
//     ProjectCreatorEmail: "paul.fuller@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "NBL 2020 Fan Development Study",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1_XkPp4PwIw0FROGbk8D5nSILII09KAif",
//     CostingsFolderId: "1AP6y7osm03swgaxhCSeq6gdVXEmhqKmo",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 16,
//     ProjectId: "NZ1911220028",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "test",
//     BusinessUnit: "OM",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "vincent.monaghan@nielsen.com",
//     ProjectResourcesFolderId: "1sehLl0uYyy3evRrU9sBBtczym2fn_lTR",
//     CostingsFolderId: "1_3nioj93LuMdeNXhpYyT0UOqEIJZ9JZ_",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 17,
//     ProjectId: "NZ1911220029",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "July Annual update",
//     BusinessUnit: "HSOR",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040,FM000010",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1dts-JXSaxq4sQ5abcotjaSt9hVOKu-d1",
//     CostingsFolderId: "1uga9P-GBhQEOG1LrXKO3HNcycozBxUcU",
//     CommissionedProfileId: 38,
//     CommissionedBy: "melissa.graham@nielsen.com",
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 18,
//     ProjectId: "NZ1911220030",
//     ProjectCreatorEmail: "beena.mitha@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "NZME Brand Health 2019",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "juliet.martin@nielsen.com,ami.durlabh@nielsen.com,beena.mitha@nielsen.com,jason.kok@nielsen.com",
//     ProjectResourcesFolderId: "1dXsM26ejTqjwBv1N_9xSqGsw_XCRtSRk",
//     CostingsFolderId: "1KIMYiNL0jNee3x-8gAcK-0XwWq8aFI_P",
//     CommissionedProfileId: 39,
//     CommissionedBy: "beena.mitha@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "susan.bonnar@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 19,
//     ProjectId: "NZ1911220031",
//     ProjectCreatorEmail: "beena.mitha@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Mix Ltd AU Brand Health W2 2019",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "tessa.hoffman@nielsen.com,juliet.martin@nielsen.com,beena.mitha@nielsen.com,jason.kok@nielsen.com,ami.durlabh@nielsen.com,beena.mitha@nielsen.com",
//     ProjectResourcesFolderId: "1jfylm29TEN9h_BIoGPxg2DnEVxWTbuc1",
//     CostingsFolderId: "1iszJsCyW5gPEZYxXvXZjzcKd11jOZWgO",
//     CommissionedProfileId: 60,
//     CommissionedBy: "beena.mitha@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "beth.cameron@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: true,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 20,
//     ProjectId: "AU1911230032",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "PepsiCo_Employer Branding_Sep 19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "frank.caristo@nielsen.com,mario.lausberg@nielsen.com,darshana.geeganage@nielsen.com",
//     ProjectResourcesFolderId: "1cG6txL-6E2E4_Ak6pov_0Yyvfk3cn0o_",
//     CostingsFolderId: "1WNWKZZXJPsHv_AmTEHMMwoeLMgI-DMVZ",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 21,
//     ProjectId: "AU1911230033",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "test",
//     BusinessUnit: "MA",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1u42JBvOHwO8NT7ZqB7485htWgKi80w3V",
//     CostingsFolderId: "1HCTwu9A_3f0PtIRE0ami2SWe-A0ipuhP",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 22,
//     ProjectId: "AU1911250034",
//     ProjectCreatorEmail: "chanel.stoyle@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Simplot_John West Tracking Dip_Nov19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "chanel.stoyle@nielsen.com,tibin.jose@nielsen.com",
//     ProjectResourcesFolderId: "1TwJGQXKpaDIH_mcaZiYE95pTNSuOyXta",
//     CostingsFolderId: "13m36uotmbOwUjOqcMZOUFWFIRYaeDq9m",
//     CommissionedProfileId: 43,
//     CommissionedBy: "tibin.jose@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "shyiana.wiria@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 23,
//     ProjectId: "AU1911250035",
//     ProjectCreatorEmail: "aaron.cooper@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "EPL Clubs",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1wbFZOR1fjP71k-O5YuI8_QaS7W3OAglR",
//     CostingsFolderId: "1D7qMjJb2KTmmBb0Lbpinoh5v5XOOfOU-",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 24,
//     ProjectId: "AU1911250036",
//     ProjectCreatorEmail: "rob.o'dwyer@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Matisse & Picasso Event Research :",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "james.loynd@nielsen.com,rob.o'dwyer@nielsen.com,chris.rankin@nielsen.com",
//     ProjectResourcesFolderId: "15yNTnr3omYN_kvpaZTaebY8SgrXkodU7",
//     CostingsFolderId: "1wM86CbcLKVjS8Oql8gFxjMSUASN11yp7",
//     CommissionedProfileId: 45,
//     CommissionedBy: "rob.o'dwyer@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "beth.cameron@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 25,
//     ProjectId: "AU1911250037",
//     ProjectCreatorEmail: "avinaesh.kandasamy@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Economic Impact Analyis - Boxing Day Test",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "steve.whately@nielsen.com",
//     ProjectResourcesFolderId: "1r79FA_BF12noB9cWKPneGK6cujWqlMxA",
//     CostingsFolderId: "1D2T8PhHTnveS3bQT8-hTaBzyMgRseQ92",
//     CommissionedProfileId: 46,
//     CommissionedBy: "avinaesh.kandasamy@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "stefi.wenas@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 26,
//     ProjectId: "AU1911250038",
//     ProjectCreatorEmail: "ben.x.allen@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Brand Ambassador Analysis",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1TXJuiu46SKJ7Fx5bNkTChQ8_qrXJo7ZZ",
//     CostingsFolderId: "1Q_XCgq4ZN6waTLqG89Mpj6Ym-9AnC3WZ",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 27,
//     ProjectId: "AU1911250039",
//     ProjectCreatorEmail: "paul.fuller@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Test",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1Fwd8RHbfLiBICEYj4gIl8ltRaXqsVDQ9",
//     CostingsFolderId: "10lwJgyq4l67XciHmvc2DHDkZWVUHg4M2",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 28,
//     ProjectId: "AU1911250040",
//     ProjectCreatorEmail: "avinaesh.kandasamy@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Economic Impact Analysis",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "steve.whately@nielsen.com",
//     ProjectResourcesFolderId: "1gM3o_YxKYPBWnV-pZ4JkXFjD66F2myNM",
//     CostingsFolderId: "12J_4m38s7Pf1f_mRVyXbA77LKwDoDYyN",
//     CommissionedProfileId: 51,
//     CommissionedBy: "avinaesh.kandasamy@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "stefi.wenas@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 29,
//     ProjectId: "AU1911250041",
//     ProjectCreatorEmail: "aaron.cooper@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "EPL Clubs Fanbases",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1a9jC5j72xcMMzN456I7H2rDo9zeuPXPe",
//     CostingsFolderId: "1yRTSUOJBjKPsUJj9ribelv0d6f_t8HeQ",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 30,
//     ProjectId: "AU1911260042",
//     ProjectCreatorEmail: "aashish.negi@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "IAG_AU_NRMA QLD_Sample Boost",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: null,
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "nathan.bale@nielsen.com",
//     ProjectResourcesFolderId: null,
//     CostingsFolderId: null,
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: false,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 31,
//     ProjectId: "AU1911260043",
//     ProjectCreatorEmail: "natalie.yeo@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "IAG_AU_NRMA QLD_Sample Boost",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "nathan.bale@nielsen.com",
//     ProjectResourcesFolderId: "1NszRf6mR6tKlXh7rc60qqMywVFD7BbrS",
//     CostingsFolderId: "1FP931QxcNm7pMa_PKa0-9WBMTjKzLyGr",
//     CommissionedProfileId: 52,
//     CommissionedBy: "natalie.yeo@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "jason.fowell@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 32,
//     ProjectId: "AU1911260044",
//     ProjectCreatorEmail: "reem.elgohary@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Blackmores EPO",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000004",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "16RJ0YNuiivoXZGhhsIa3Ja5H4bpIHmr7",
//     CostingsFolderId: "1wwGdxx-2MfuFmJQ2KNfQNZdq-RtyBkt5",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 33,
//     ProjectId: "AU1911270045",
//     ProjectCreatorEmail: "darshana.geeganage@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "DiaGeo_Shopper Decision Process_2020",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "2",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "",
//     ProjectResourcesFolderId: "1SdWUeXzjop04Ao3wtvRJ2dUARuZLL2YY",
//     CostingsFolderId: "1bWd3acmMbOYEOrjNnptsFpKkFCcolqw7",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 34,
//     ProjectId: "AU1911270050",
//     ProjectCreatorEmail: "chanel.stoyle@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Coles_Signage and Communication Eye Tracking_Dec19",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000041",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1h5KIUkFegn3de-EuL9TQjBSUoytPK9n3",
//     CostingsFolderId: "1ROwu-IrnqK-LGXWd1qCHsm-f4xv1krmQ",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 35,
//     ProjectId: "AU1911270051",
//     ProjectCreatorEmail: "aaron.cooper@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "EPL quick Poll",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1G4SsVal4H1GilmRgbf1_S7U1IzCfbJXz",
//     CostingsFolderId: "1c_Iarp8FJ9EYas6EHcOx57br8V4rTUT8",
//     CommissionedProfileId: 59,
//     CommissionedBy: "aaron.cooper@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 36,
//     ProjectId: "NZ1911280052",
//     ProjectCreatorEmail: "beena.mitha@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "CI_CSAIR_Brand Health 2019",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "arlene.sison@nielsen.com,juliet.martin@nielsen.com,beena.mitha@nielsen.com,jason.kok@nielsen.com,ami.durlabh@nielsen.com,beena.mitha@nielsen.com",
//     ProjectResourcesFolderId: "1Scy_zrCpSbl9x_T6GFzjTa4ulYH36nEF",
//     CostingsFolderId: "16Zo-VJbSqmR8gMOaIJbqVTlEq5QaTKhZ",
//     CommissionedProfileId: 61,
//     CommissionedBy: "beena.mitha@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "beth.cameron@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: true,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 37,
//     ProjectId: "AU1911280053",
//     ProjectCreatorEmail: "aashish.negi@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Aashish Test Please Ignore",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040,FM000009",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "13bUu565w_w4z37NG4ibjoWg_gnYFxQK3",
//     CostingsFolderId: "1BVD1Rtgko3CyzoCU72hT0c47xNb_G-56",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 38,
//     ProjectId: "NZ1911290054",
//     ProjectCreatorEmail: "wendy.stockwell@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "CI_Comms_Council_Project Pipeline",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000009",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "wendy.stockwell@nielsen.com",
//     ProjectResourcesFolderId: "1y19QcJc3R1LAUD3DcyYUGbbCdU_cWpT2",
//     CostingsFolderId: "1gJjHKJlFd_Kl629BmRwYQTBDSSYwOhnM",
//     CommissionedProfileId: 67,
//     CommissionedBy: "wendy.stockwell@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "alison.minhinnick@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 39,
//     ProjectId: "AU1911290055",
//     ProjectCreatorEmail: "ellen.purvis@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Australia Swims Campaign Research - 2020",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "2",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "ellen.purvis@nielsen.com",
//     ProjectResourcesFolderId: "1SJlD1puc5HjHov5xYe4PhWVovvpukAII",
//     CostingsFolderId: "1c55FLYCa15e-33VsWoYeufP5SEXQVU9W",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 40,
//     ProjectId: "AU1911290056",
//     ProjectCreatorEmail: "lucy.x.lu@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Hort Veg P12 + Lapsed + HHB Sustainability",
//     BusinessUnit: "HSOR",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: true,
//     Methodology: "FM000040",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1GKk1IuksUDidlPizkb3OuPDVBMNiN9Pa",
//     CostingsFolderId: "1H4lHoaWHUCjPnVaVjgcVIiNiTfW0oTzA",
//     CommissionedProfileId: 69,
//     CommissionedBy: "lucy.x.lu@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 41,
//     ProjectId: "AU1912020057",
//     ProjectCreatorEmail: "shruthi.babu@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "NBN Operational Panel Survey",
//     BusinessUnit: "MA",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: null,
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: null,
//     CostingsFolderId: null,
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: false,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 42,
//     ProjectId: "NZ1912020058",
//     ProjectCreatorEmail: "nick.stace@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Super Club Netball Post-Event Attendee Research",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "shruthi.babu@nielsen.com",
//     ProjectResourcesFolderId: "1VfMPxWcrqu7HoKFqAy2KL3i389pQakOo",
//     CostingsFolderId: "1VfMPxWcrqu7HoKFqAy2KL3i389pQakOo",
//     CommissionedProfileId: 70,
//     CommissionedBy: "nick.stace@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "stefi.wenas@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 43,
//     ProjectId: "AU1912020059",
//     ProjectCreatorEmail: "julian.marucci@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "AUS December 2019 Annual Update Online",
//     BusinessUnit: "HSOR",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "3",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1sDvyAaZsEaR51dE_lFDns-kcSnRWvThy",
//     CostingsFolderId: "1sDvyAaZsEaR51dE_lFDns-kcSnRWvThy",
//     CommissionedProfileId: 71,
//     CommissionedBy: "julian.marucci@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 44,
//     ProjectId: "AU1912020060",
//     ProjectCreatorEmail: "steve.whately@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "Tennis Australia - AO New Global Audiences - 2020 Research",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "steve.whately@nielsen.com,shruthi.babu@nielsen.com",
//     ProjectResourcesFolderId: "1sFVb5Nqf-HdZYHFhWyClaMM31I0zw7l-",
//     CostingsFolderId: "1KGACsjAgPjR8ElMVZV1uP7r4gqvOvi6_",
//     CommissionedProfileId: 72,
//     CommissionedBy: "steve.whately@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 45,
//     ProjectId: "AU1912030061",
//     ProjectCreatorEmail: "kayla.ramiscal@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: 'Publicis Rate Card"',
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "shruthi.babu@nielsen.com",
//     ProjectResourcesFolderId: "1yMNqaoVsK2j9BdIPzJpu6x4WU1dgEyFR",
//     CostingsFolderId: "164bcEksirQ2Vk2_tpbEKaCqo6VMKG_Ke",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 46,
//     ProjectId: "NZ1912030062",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "test",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ2",
//     IsSyndicated: false,
//     Methodology: "FM000004",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1tB1ofyOgyzfCaXiWcitkQPcxV-GG78lb",
//     CostingsFolderId: "1oLBCuJHP5Kzaiv40HfFxnFSAia6Ccd8_",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 47,
//     ProjectId: "AU1912030063",
//     ProjectCreatorEmail: "kayla.ramiscal@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: 'Publicis Rate Card" (Pre & Post)',
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: "shruthi.babu@nielsen.com",
//     ProjectResourcesFolderId: "1IwfiB51VsDaIudpXlPZX7fF_byq5HnQ4",
//     CostingsFolderId: "1sqWv_h8CezxfNOLLLn2XkK5P_ROvTuXb",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 48,
//     ProjectId: "AU1912030064",
//     ProjectCreatorEmail: "steve.whately@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "L'Oreal - ROSI - Nov19",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "4",
//     ProposalOwnerEmail: null,
//     OtherContactEmails:
//       "steve.whately@nielsen.com,aaron.cooper@nielsen.com,chris.rankin@nielsen.com",
//     ProjectResourcesFolderId: "1Ynl1q7JAyAuoV2nlJrd6EKNLyx73D6sj",
//     CostingsFolderId: "1Akfr1HCLYiljd0uYBwESpzG7WZKLgh4Q",
//     CommissionedProfileId: 79,
//     CommissionedBy: "steve.whately@nielsen.com",
//     IsDeleted: false,
//     IsDraftProposal: true,
//     ProjectManagerEmail: "shyiana.wiria@nielsen.com",
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 49,
//     ProjectId: "NZ1912050065",
//     ProjectCreatorEmail: "melissa.graham@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "testing notifications",
//     BusinessUnit: "CI",
//     IndustryVertical: null,
//     CommissioningCountry: "NZ",
//     CommissioningOffice: "NZ1",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "16lta1p9bxAmAPaHkPmDYPBmfpcUZcdZh",
//     CostingsFolderId: "1To_11c3sjEJNEMh8WHxTF3dFKlGQ9POB",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
//   {
//     id: 50,
//     ProjectId: "AU1912050066",
//     ProjectCreatorEmail: "angela.mata@nielsen.com",
//     ProjectCreatorName: null,
//     ProjectName: "AU open",
//     BusinessUnit: "NS",
//     IndustryVertical: null,
//     CommissioningCountry: "AU",
//     CommissioningOffice: "AU2",
//     IsSyndicated: false,
//     Methodology: "FM000040",
//     ProjectStatus: "1",
//     ProposalOwnerEmail: null,
//     OtherContactEmails: null,
//     ProjectResourcesFolderId: "1cno77B1xf7EgiDtLkFbDO3svmTERV_cJ",
//     CostingsFolderId: "1aTelUxGDi2lCkXLntJBkqhvIMCVw4_oT",
//     CommissionedProfileId: null,
//     CommissionedBy: null,
//     IsDeleted: true,
//     IsDraftProposal: true,
//     ProjectManagerEmail: null,
//     LastRefreshSF: null,
//     IsSFContactSyncPaused: false,
//     IsGdriveActionActive: false,
//     LastUpdatedBy: null,
//     createdAt: "2020-08-24T07:15:08.000Z",
//     updatedAt: "2020-08-24T07:15:08.000Z",
//   },
// ];
